// app/tooltip/tooltip.component.ts
import { Component, Input } from '@angular/core';
import { default as PfTooltip } from '../web-components/pf-tooltip/pf-tooltip.component';

customElements.define('pf-tooltip', PfTooltip);

@Component({
  selector: 'pf-tooltip-component',
  templateUrl: './tooltip.component.html'
})
export class TooltipComponent {
  /**
   * The Tooltip placement
   */
  @Input() placement: string;

  /**
   * The Tooltip target selector
   */
  @Input() targetSelector: string;

  /**
   * The Tooltip container selector
   */
  @Input() containerSelector: string;

  /**
   * The Tooltip animation class
   */
  @Input() animation: string;

  /**
   * The Tooltip animation delay
   */
  @Input() delay: string;

  /**
   * The Tooltip animation duration
   */
  @Input() duration: string;

  /**
   * The Tooltip text
   */
  @Input() tooltipText: string;

  constructor() {}
}

// frameworks/react/src/Tooltip/Tooltip.js
import React, { PropTypes } from 'react'
import { PfTooltip } from '../index.js'

customElements.define('pf-tooltip', PfTooltip)

/**
 * Tooltip Component for Patternfly React
 */
class Tooltip extends React.Component {
  componentDidUpdate() {
    this.handleContentChanged()
  }

  componentDidMount() {
    this.handleContentChanged()
  }

  handleContentChanged() {
    var event = new CustomEvent('pf-tooltip.handleContentChanged', {})
    if (this.pfTooltip) {
      this.pfTooltip.dispatchEvent(event)
    }
  }

  render() {
    const { targetSelector, containerSelector, children } = this.props
    let customAttributes = {
      'target-selector': targetSelector,
      'container-selector': containerSelector
    }
    return (
      <pf-tooltip
        ref={tooltip => {
          this.pfTooltip = tooltip
        }}
        {...this.props}
        {...customAttributes}
      >
        {children}
      </pf-tooltip>
    )
  }
}

Tooltip.propTypes = {
  /** the animation class */
  animation: PropTypes.string, // eslint-disable-line react/no-unused-prop-types
  /** the target element selector */
  targetSelector: PropTypes.string,
  /** left, right, top, bottom placement */
  placement: PropTypes.string, // eslint-disable-line react/no-unused-prop-types
  /** animation delay (ms) */
  delay: PropTypes.number, // eslint-disable-line react/no-unused-prop-types
  /** animation duration (ms) */
  duration: PropTypes.number, // eslint-disable-line react/no-unused-prop-types
  /** the container element selector */
  containerSelector: PropTypes.string,
  /** children nodes */
  children: PropTypes.node
}

export default Tooltip
