// frameworks/angular/src/app/hello/hello.component.ts
import { Component, Input } from '@angular/core';
import { define } from 'skatejs';
import { default as PfHello } from '../web-components/pf-hello/pf-hello.component';

define(PfHello);

@Component({
  selector: 'pf-hello-component',
  templateUrl: './hello.component.html',
  styleUrls: ['./hello.component.css']
})
export class HelloComponent {
  /**
   * The Tooltip placement
   */
  @Input() name: string;

  constructor() {}
}

// frameworks/react/src/Hello/Hello.js
import React from 'react'
import PropTypes from 'prop-types'

import { define } from 'skatejs'
import { PfHello } from '../index.js'

define(PfHello)

/**
 * Hello Component for Patternfly React
 */
const Hello = ({ name }) => {
  const attributes = { name: name }
  return <pf-hello {...attributes} />
}
Hello.propTypes = {
  /** the name attribute  */
  name: PropTypes.string
}
Hello.defaultProps = {
  name: 'I 💗 Web Components!'
}

export default Hello
